[rpc_endpoints]
op_chain_a = "http://127.0.0.1:9545"
op_chain_b = "http://127.0.0.1:9546"

[profile.default]
src = "src"
script = "scripts"
out = "out"
libs = ["lib"]
solc_version = '0.8.25'
fs_permissions = [
    { access = 'read-write', path = './deployments/' },
    { access = 'read', path = './configs' },
    { access = 'read', path = './test' },
    { access = 'write', path = './deployment.json' },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
